services:
  rsstranslator:
    image: versun/rsstranslator
    environment:
      - SITE_URL=http://127.0.0.1:8000
      - REDIS_URL=redis://rsstranslator_redis:6379/0
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000
      - DEFAULT_TARGET_LANGUAGE=Chinese Simplified # See https://github.com/versun/RSS-Translator/blob/main/config/settings.py#L199 for optional values
      - PORT=8000
      - DEBUG=0
      - DEMO=0
      - USER_MANAGEMENT=0
      - LOG_LEVEL=ERROR
      - default_max_posts=20
    volumes:
      - ./data:/app/data
    ports:
      - 8000:8000
    restart: always
    healthcheck:
      test: ["CMD", "python", "-c", "import redis,os; r=redis.Redis.from_url(os.getenv('REDIS_URL')); r.ping()"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      - rsstranslator_redis
  
  rsstranslator_redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
