# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: RSSBox
site_url: https://rssbox.app
site_author: versun
site_description: >-
  Translate RSS feeds to your language

# Repository
repo_name: versun/rssbox
repo_url: https://github.com/versun/rssbox

# Copyright
copyright: Copyright &copy; 2023 - 2025 Versun

theme:
  name: terminal # https://github.com/ntno/mkdocs-terminal
  palette: gruvbox_dark
  features:
    - footer.prev_next
    #- navigation.side.hide
    - navigation.side.indexes
    #- navigation.side.toc.hide
    - navigation.top.hide
    #- navigation.top.cursor_animation.hide
    #- navigation.top.search_button.hide
    - revision.date
    - revision.history
    #- style.links.underline.hide
  favicon: assets/logo.ico
  logo: assets/logo.ico

markdown_extensions:
  # Python Markdown
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - docs

plugins:
  - md-to-html
  - git-revision-date
  - macros
  - search
  - i18n:
        docs_structure: folder
        languages:
          - locale: zh
            default: true
            name: 中文
            build: true
          - locale: en
            name: English
            build: true
            nav_translations:
              主页: Home
              安装: Install
              一键部署: One Click
              Docker安装: Docker
              开启SSL: Enable SSL
              使用说明: Guide
              翻译服务: Translate Services
              常见问题: FAQ
              开发进度: Roadmap
              赞助: Sponsorship



# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/versun/rssbox
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/versun/rssbox
    - icon: fontawesome/brands/telegram
      link: https://t.me/rssboxapp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VersunPan

# Page tree
nav:
  - 主页: index.md
  - Demo: demo.md
  - 安装:
      - Docker安装: install/docker.md
      - 一键部署: install/one-click.md
  - 开启SSL: ssl.md
  - 使用说明: guide.md
  - 翻译服务: translator.md
  - 常见问题: faq.md
  - 开发进度: https://github.com/users/versun/projects/8
  - 赞助: https://rssbox.app/#_2
  - Github: https://github.com/versun/rssbox
  - Telegram: https://t.me/rssboxapp
  - Releases: https://github.com/versun/rssbox/releases
